[ISSUE #677]ks-manager重启会导致部分信息采集抛出空指针
didi/KnowStreaming pull request #688
Opened 2022-10-14 14:55 UTC by haoqi123

请不要在没有先创建Issue的情况下创建Pull Request。

## 变更的目的是什么

修复ks-manager重启会导致部分信息采集抛出空指针

## 简短的更新日志

1. 调整`BrokerMetricESDAO.java` `ClusterMetricESDAO.java` `GroupMetricESDAO.java` `TopicMetricESDAO.java`中对指标空值的处理
2. 添加对应测试方法

## 验证这一变化
后台不抛出异常，页面展示时该段时间数据缺失
<img width="1678" alt="image" src="https://user-images.githubusercontent.com/49672871/195877093-3a4c4ea8-5587-4a5d-8c03-74bfab90efdf.png">

请遵循此清单，以帮助我们快速轻松地整合您的贡献：

* [x] 确保有针对更改提交的 Github issue（通常在您开始处理之前）。诸如拼写错误之类的琐碎更改不需要 Github issue。您的Pull Request应该只解决这个问题，而不需要进行其他更改——  一个 PR 解决一个问题。
* [x] 格式化 Pull Request 标题，如[ISSUE #xxxx] support Confluent Schema Registry。 Pull Request 中的每个提交都应该有一个有意义的主题行和正文。
* [x] 编写足够详细的Pull Request描述，以了解Pull Request的作用、方式和原因。
* [x] 编写必要的单元测试来验证您的逻辑更正。如果提交了新功能或重大更改，请记住在test 模块中添加 integration-test
* [x] 确保编译通过，集成测试通过

2022-10-14 14:57 UTC, haoqi123 commented
对于页面上指标中断，这样展示是否合理？

2022-10-15 06:30 UTC, ZQKC commented
> 对于页面上指标中断，这样展示是否合理？

1、原先会在缺失的点上进行补点，现在调整为缺点即不显示，这个变动我周一拉产品一起沟通确认一下啊；
2、代码上由原先的obj.toString()调整为String.valueOf()这块，我先验证一下效果，晚点给你答复啊；

2022-10-19 08:50 UTC, ZQKC commented
关于第一点，出现点中断时页面直接断点了，这块建议还是维持原先的效果，原因如下：
1、从数据准确性角度上看，确实展示真实数据是最好的情况，平台也需要尽量减少中断的情况出现，但是实际上平台避免不了会出现指标中断，而且指标中断时会误导用户，因此考虑维持原先的逻辑。

2022-10-19 13:34 UTC, haoqi123 commented
> 关于第一点，出现点中断时页面直接断点了，这块建议还是维持原先的效果，原因如下： 1、从数据准确性角度上看，确实展示真实数据是最好的情况，平台也需要尽量减少中断的情况出现，但是实际上平台避免不了会出现指标中断，而且指标中断时会误导用户，因此考虑维持原先的逻辑。

好的，麻烦了，我调整下代码

2022-10-20 02:54 UTC, ZQKC commented on km-persistence/src/main/java/com/xiaojukeji/know/streaming/km/persistence/es/dao/BrokerMetricESDAO.java
> +            Object valueObj = esAggrMap.get(metric).getUnusedMap().get(VALUE);
原先的问题是这里没有判空逻辑导致一直抛空指针，日志量很大，所以解决方式是否可以考虑：
1、增加对数据为空的判断，如果为空，则直接continue，不进行toString()。
2、这里不建议直接缺少点就直接补0，可以看一下后面的逻辑，后面有代码单独进行补数据的逻辑。

2022-10-20 02:56 UTC, ZQKC requested changes
1、代码上已进行评论；
2、辛苦将多个commit合并为一个，commit log的标题可以为[ISSUE #677] 重启会导致部分信息采集抛出空指针

2022-10-20 03:25 UTC, haoqi123 commented on km-persistence/src/main/java/com/xiaojukeji/know/streaming/km/persistence/es/dao/BrokerMetricESDAO.java
> +            Object valueObj = esAggrMap.get(metric).getUnusedMap().get(VALUE);
太好了，我在调整的时候就在想要不要改成continue，我稍后调整代码

2022-10-20 04:04 UTC, haoqi123 commented
> 1、代码上已进行评论； 2、辛苦将多个commit合并为一个，commit log的标题可以为[ISSUE #677] 重启会导致部分信息采集抛出空指针

关于test中的代码还需要调整吗?

2022-10-20 05:35 UTC, ZQKC reviewed
已在相关代码上做评论，无其他内容。后续可以考虑把集群ID，Topic名称这些公共的东西抽出来搞个全局变量什么的。

2022-10-20 05:35 UTC, ZQKC commented on km-rest/src/test/java/com/xiaojukeji/know/streaming/km/persistence/es/ClusterMetricESDAOTest.java
> +        List<String> metrics    = Arrays.asList("Connections","BytesIn_min_15","PartitionURP",
这里的格式上，可以考虑对齐一下比如
```
List<String> metrics    = Arrays.asList(
    Connections,        PartitionURP,        Partitions,
    BytesIn_min_15,   Zookeepers,         HealthScore_Groups      
);
```

非必需，看个人习惯，仅仅是个人感觉这里代码堆在一起有点不整齐的感觉。

2022-10-20 05:57 UTC, haoqi123 commented on km-rest/src/test/java/com/xiaojukeji/know/streaming/km/persistence/es/ClusterMetricESDAOTest.java
> +        List<String> metrics    = Arrays.asList("Connections","BytesIn_min_15","PartitionURP",
关于调整test中的重复变量，要不，等下一个feature吧~~

2022-10-20 07:15 UTC, ZQKC commented on km-rest/src/test/java/com/xiaojukeji/know/streaming/km/persistence/es/ClusterMetricESDAOTest.java
> +        List<String> metrics    = Arrays.asList("Connections","BytesIn_min_15","PartitionURP",
可以的

2022-10-20 07:36 UTC, merged