部署文档添加 ubuntu安装mysql
didi/KnowStreaming pull request #701
Opened 2022-10-18 15:40 UTC by SimonTeo58

请不要在没有先创建Issue的情况下创建Pull Request。

## 变更的目的是什么
添加ubuntu平台安装mysql步骤

## 简短的更新日志

-- 部署文档添加ubuntu平台安装mysql步骤

## 验证这一变化

请遵循此清单，以帮助我们快速轻松地整合您的贡献：

* [ ] 确保有针对更改提交的 Github issue（通常在您开始处理之前）。诸如拼写错误之类的琐碎更改不需要 Github issue。您的Pull Request应该只解决这个问题，而不需要进行其他更改——  一个 PR 解决一个问题。
* [ ] 格式化 Pull Request 标题，如[ISSUE #123] support Confluent Schema Registry。 Pull Request 中的每个提交都应该有一个有意义的主题行和正文。
* [ ] 编写足够详细的Pull Request描述，以了解Pull Request的作用、方式和原因。
* [ ] 编写必要的单元测试来验证您的逻辑更正。如果提交了新功能或重大更改，请记住在test 模块中添加 integration-test
* [ ] 确保编译通过，集成测试通过

2022-10-19 02:40 UTC, ZQKC requested changes
1、需要将多个commit合并为一个；
2、看提交内容，超出了PR描述的内容；
3、提交内容存在问题部分已进行评论；

2022-10-19 04:12 UTC, SimonTeo58 commented on install.sh
> +#!/bin/sh
sorry,加入了无关的文件

2022-10-19 08:11 UTC, ZQKC commented
后续所有的文档会在官网 https://doc.knowstreaming.com/product/1-brief-introduction 上进行维护，github暂时不会进行维护，因此本需求可以私下沟通啊

2022-10-23 01:42 UTC, ZQKC commented on install.sh
> +#!/bin/sh
这个文件看着好像还在

2022-10-23 01:43 UTC, ZQKC commented
看着虽然评论了，但是代码好像还没有修改，是忘记提交了吗😂

2022-10-23 03:02 UTC, SimonTeo58 commented
reject 这个PR吧，我再去改改其他issue

2022-10-23 03:02 UTC, closed without merging