[Bugfix] 修复新建Topic后，立即查看Topic-Messages信息会提示Topic不存在的问题 (#697)
didi/KnowStreaming pull request #720
Opened 2022-10-24 00:45 UTC by RenChauncy

请不要在没有先创建Issue的情况下创建Pull Request。

## 变更的目的是什么

修复创建完topic直接查message显示topic不存在问题。

## 简短的更新日志

把topic信息写入到db时候，增加延时任务，查询partition信息，写入DB。

## 验证这一变化

创建topic后，过3秒查询，不会提示没有partition。

请遵循此清单，以帮助我们快速轻松地整合您的贡献：

* [ ] 确保有针对更改提交的 Github issue（通常在您开始处理之前）。诸如拼写错误之类的琐碎更改不需要 Github issue。您的Pull Request应该只解决这个问题，而不需要进行其他更改——  一个 PR 解决一个问题。
* [ ] 格式化 Pull Request 标题，如[ISSUE #123] support Confluent Schema Registry。 Pull Request 中的每个提交都应该有一个有意义的主题行和正文。
* [ ] 编写足够详细的Pull Request描述，以了解Pull Request的作用、方式和原因。
* [ ] 编写必要的单元测试来验证您的逻辑更正。如果提交了新功能或重大更改，请记住在test 模块中添加 integration-test
* [ ] 确保编译通过，集成测试通过

2022-10-24 05:32 UTC, ZQKC requested changes
1、代码修改已在相关代码位置；
2、辛苦合并多个commit为一个，此外，commit-log的最后面，不需要是`(didi#679)`，只需要`(#679)`这样就可以了。

2022-10-24 05:32 UTC, ZQKC commented on km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/partition/impl/PartitionServiceImpl.java
> +                Result<List<Partition>> partitionListRes = this.getPartitionsFromAdminClientByClusterTopicName(clusterPhy, topicName);
感觉这块的逻辑和之前有点不一样了。之前是只要一个出错，直接抛出异常返回了，现在看着是一定不会有异常了。

2022-10-24 05:32 UTC, ZQKC commented on km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/partition/impl/PartitionServiceImpl.java
> +    public Result<List<Partition>> listPartitionFromKafkaByClusterTopicName(ClusterPhy  clusterPhy, String topicName) {
个人觉得这个方法依旧可以叫listPartitionsFromKafka，和上面那个不同的是入参不一样罢了。

2022-10-26 02:11 UTC, ZQKC requested changes
已在相关代码进行评论

2022-10-26 02:11 UTC, ZQKC commented on km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/partition/impl/PartitionServiceImpl.java
> +                    return Result.buildFail();
不要直接返回Result.buildFail()，可以使用Result.buildFromIgnoreData(partitionListRes);

2022-10-26 02:11 UTC, ZQKC commented on km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/partition/impl/PartitionServiceImpl.java
> +
方法开头一般不需要有什么空格。

2022-10-26 02:11 UTC, ZQKC commented on km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/partition/impl/PartitionServiceImpl.java
> +            return Result.buildFailure(ResultStatus.KAFKA_OPERATE_FAILED);
原先代码返回的是：
return Result.buildFromRSAndMsg(ResultStatus.KAFKA_OPERATE_FAILED, e.getMessage());

现在的返回是：
return Result.buildFailure(ResultStatus.KAFKA_OPERATE_FAILED);

尽量不要修改已有代码的语义啊。

2022-10-26 15:14 UTC, RenChauncy commented on km-core/src/main/java/com/xiaojukeji/know/streaming/km/core/service/partition/impl/PartitionServiceImpl.java
> +
是上面的空行吧

2022-10-27 03:04 UTC, merged